name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Install packages
        run: pipenv install
      - name: Run Notebook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: pipenv run jupyter nbconvert --execute --clear-output *.ipynb
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: dist
          jekyll: false
          commit_message: "chore: 🚀 deploy to GitHub pages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
